#!/usr/bin/env python3
"""generate.py — emits generated.go from the vendored v2 registries.

Sources (vendored at CORPUS_TAG by scripts/check-vendored-sync.mjs):
    spec/v2/errors.json                 -> ErrorCodes / ErrorCodeHTTPStatus / RetriableErrorCodes / IsErrorCode
    schemas/v2/capabilities.schema.json -> CapabilityMetadataKeys / CapabilityFamilyKeys / IsCapabilityFamilyKey

``python3 scripts/generate.py`` rewrites generated.go; ``--check`` exits 1 when
the committed file differs (the sdks:check gate runs it). Stdlib only; the
output is gofmt-shaped (tabs, one literal per line, no aligned columns).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PKG = HERE.parent
REPO = PKG.parent.parent
OUT = PKG / "generated.go"


def main() -> int:
    errors = json.loads((REPO / "spec/v2/errors.json").read_text())
    caps = json.loads((REPO / "schemas/v2/capabilities.schema.json").read_text())

    rows = sorted(errors["rows"], key=lambda r: r["code"])
    codes = [r["code"] for r in rows]
    if len(set(codes)) != len(codes):
        raise SystemExit("errors.json: duplicate code")
    retriable = [r["code"] for r in rows if r.get("retriable") is True]

    family_keys: list[str] = []
    metadata_keys: list[str] = []
    for key, schema in caps.get("properties", {}).items():
        req = schema.get("required") if isinstance(schema, dict) else None
        req = req if isinstance(req, list) else []
        (family_keys if "status" in req and "witness" in req else metadata_keys).append(key)
    family_keys.sort()
    metadata_keys.sort()
    if caps.get("additionalProperties") is not False:
        raise SystemExit("capabilities.schema.json: root is not closed")

    # RE2 has no lookahead: the registry pattern's `(?!openwop\.)` guard is
    # applied by IsVendorErrorCode as a prefix check instead.
    pattern = errors["vendorCodePattern"]
    guard = "(?!openwop\\.)"
    if guard not in pattern:
        raise SystemExit("errors.json: vendorCodePattern lost its openwop. guard")
    pattern = pattern.replace(guard, "")

    def lines(items: list[str]) -> str:
        return "".join(f'\t"{c}",\n' for c in items)

    out = (
        "// Code generated by scripts/generate.py from spec/v2/errors.json and "
        "schemas/v2/capabilities.schema.json; DO NOT EDIT.\n"
        "//\n"
        f"// Registry version {errors['version']}, updated {errors['updated']}: {len(codes)} error codes; "
        f"{len(family_keys)} capability families, {len(metadata_keys)} metadata keys — both vendored at CORPUS_TAG.\n"
        "// `python3 scripts/generate.py` rewrites this file; `--check` fails on drift.\n"
        "\n"
        "package openwopclient\n"
        "\n"
        'import "regexp"\n'
        "\n"
        "// ErrorCodes lists every registered v2 error code (spec/v2/errors.json), sorted.\n"
        "var ErrorCodes = []string{\n" + lines(codes) + "}\n"
        "\n"
        "// errorCodeHTTPStatuses is parallel to ErrorCodes (RFC 0171 §B.1).\n"
        "var errorCodeHTTPStatuses = []int{\n"
        + "".join(f"\t{r['httpStatus']},\n" for r in rows)
        + "}\n"
        "\n"
        "// RetriableErrorCodes lists the codes registered retriable: true; retry\n"
        "// timing lives in Retry-After only (RFC 0171 §B.2).\n"
        "var RetriableErrorCodes = []string{\n" + lines(retriable) + "}\n"
        "\n"
        "// VendorErrorCodePattern is the grammar of a vendor error code, <org>.<name>,\n"
        "// without the registry's `(?!openwop\\.)` guard (RE2 has no lookahead);\n"
        "// IsVendorErrorCode applies the reserved-prefix rule.\n"
        f"var VendorErrorCodePattern = regexp.MustCompile(`{pattern}`)\n"
        "\n"
        "// CapabilityMetadataKeys lists the root metadata keys of the closed v2\n"
        "// discovery document (capabilities.md §3.1).\n"
        "var CapabilityMetadataKeys = []string{\n" + lines(metadata_keys) + "}\n"
        "\n"
        "// CapabilityFamilyKeys lists the root capability-record keys of the closed\n"
        "// v2 discovery document (capabilities.md §5–§6).\n"
        "var CapabilityFamilyKeys = []string{\n" + lines(family_keys) + "}\n"
        "\n"
        "var errorCodeHTTPStatus = map[string]int{}\n"
        "\n"
        "var retriableErrorCodeSet = map[string]struct{}{}\n"
        "\n"
        "var capabilityFamilyKeySet = map[string]struct{}{}\n"
        "\n"
        "func init() {\n"
        "\tfor i, code := range ErrorCodes {\n"
        "\t\terrorCodeHTTPStatus[code] = errorCodeHTTPStatuses[i]\n"
        "\t}\n"
        "\tfor _, code := range RetriableErrorCodes {\n"
        "\t\tretriableErrorCodeSet[code] = struct{}{}\n"
        "\t}\n"
        "\tfor _, key := range CapabilityFamilyKeys {\n"
        "\t\tcapabilityFamilyKeySet[key] = struct{}{}\n"
        "\t}\n"
        "}\n"
        "\n"
        "// IsErrorCode reports whether value is a registered protocol error code.\n"
        "func IsErrorCode(value string) bool {\n"
        "\t_, ok := errorCodeHTTPStatus[value]\n"
        "\treturn ok\n"
        "}\n"
        "\n"
        "// ErrorCodeHTTPStatus returns the registered HTTP status for a code, or 0\n"
        "// when the code is not registered.\n"
        "func ErrorCodeHTTPStatus(code string) int {\n"
        "\treturn errorCodeHTTPStatus[code]\n"
        "}\n"
        "\n"
        "// IsRetriableErrorCode reports whether value is registered retriable: true.\n"
        "func IsRetriableErrorCode(value string) bool {\n"
        "\t_, ok := retriableErrorCodeSet[value]\n"
        "\treturn ok\n"
        "}\n"
        "\n"
        "// IsVendorErrorCode reports whether value is a well-formed vendor code\n"
        "// (<org>.<name>, openwop. reserved); it does not check org registration.\n"
        "func IsVendorErrorCode(value string) bool {\n"
        '\tif len(value) >= 8 && value[:8] == "openwop." {\n'
        "\t\treturn false\n"
        "\t}\n"
        "\treturn VendorErrorCodePattern.MatchString(value)\n"
        "}\n"
        "\n"
        "// IsCapabilityFamilyKey reports whether key is a capability-record key of\n"
        "// the closed v2 root.\n"
        "func IsCapabilityFamilyKey(key string) bool {\n"
        "\t_, ok := capabilityFamilyKeySet[key]\n"
        "\treturn ok\n"
        "}\n"
    )

    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != out:
            print(f"  FAIL: {OUT} is stale — run `python3 scripts/generate.py` in go/v2", file=sys.stderr)
            return 1
        print(
            f"  ok: generated.go matches spec/v2/errors.json ({len(codes)} codes) + "
            f"capabilities.schema.json ({len(family_keys)} families)"
        )
        return 0
    OUT.write_text(out)
    print(f"wrote {OUT}: {len(codes)} error codes, {len(family_keys)} families, {len(metadata_keys)} metadata keys")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
