// Code generated by scripts/generate.py from spec/v2/errors.json and schemas/v2/capabilities.schema.json; DO NOT EDIT.
//
// Registry version 2.0, updated 2026-09-03: 94 error codes; 71 capability families, 16 metadata keys — both vendored at CORPUS_TAG.
// `python3 scripts/generate.py` rewrites this file; `--check` fails on drift.

package openwopclient

import "regexp"

// ErrorCodes lists every registered v2 error code (spec/v2/errors.json), sorted.
var ErrorCodes = []string{
	"audience_mismatch",
	"capability_not_provided",
	"capability_required",
	"client_version_unsupported",
	"connection_provider_conflict",
	"connection_provider_unresolved",
	"connector_action_unresolved",
	"connector_auth_expired",
	"credential_forbidden",
	"credential_not_found",
	"credential_required",
	"credential_revoked",
	"credential_scope_unsupported",
	"credential_unavailable",
	"delegation_chain_cyclic",
	"delegation_chain_too_long",
	"delegation_expired",
	"delegation_scope_amplified",
	"envelope_correlation_conflict",
	"envelope_invalid",
	"envelope_refusal",
	"envelope_truncation_unrecoverable",
	"event_type_unmapped",
	"forbidden",
	"force_engine_version_forbidden",
	"fork_point_invalid",
	"id_tenant_mismatch",
	"idempotency_in_flight",
	"idempotency_key_invalid",
	"idempotency_key_mismatch",
	"identity_unresolvable",
	"identity_unverified",
	"internal_error",
	"interop_version_unsupported",
	"interrupt_already_resolved",
	"interrupt_cancelled",
	"interrupt_expired",
	"interrupt_not_found",
	"interrupt_token_invalid",
	"key_revoked",
	"loop_limit_exceeded",
	"mcp_mrtr_rounds_exceeded",
	"mock_provider_forbidden",
	"not_found",
	"oauth_provider_unsupported",
	"oauth_scope_unsupported",
	"pack_dependency_conflict",
	"pack_dependency_cycle",
	"pack_engine_unsupported",
	"pack_integrity_failure",
	"pack_integrity_mismatch",
	"pack_kind_invalid",
	"pack_load_failure",
	"pack_lockfile_incomplete",
	"pack_namespace_unauthorized",
	"pack_peer_dependency_missing",
	"pack_peer_dependency_undefined",
	"pack_registry_unreachable",
	"pack_runtime_requirement_unmet",
	"pack_signature_invalid",
	"pack_validation_failed",
	"pack_version_not_found",
	"protocol_version_mismatch",
	"protocol_version_unsupported",
	"rate_limited",
	"recursion_limit_exceeded",
	"replay_diverged_at_refusal",
	"replay_memory_snapshot_unavailable",
	"replay_source_missing",
	"residency_unavailable",
	"run_already_active",
	"run_forbidden",
	"run_terminal",
	"run_timeout",
	"runner_unavailable",
	"sandbox_capability_denied",
	"sandbox_escape_attempt",
	"sandbox_memory_exceeded",
	"sandbox_timeout",
	"schedule_horizon_exceeded",
	"sender_constraint_missing",
	"signature_not_available",
	"sub_chain_cycle",
	"sub_chain_depth_exceeded",
	"token_budget_exceeded",
	"unauthenticated",
	"unsupported_stream_mode",
	"until_in_past",
	"validation_error",
	"version_conflict",
	"webhook_url_rejected",
	"workspace_conflict",
	"workspace_membership_required",
	"workspace_too_large",
}

// errorCodeHTTPStatuses is parallel to ErrorCodes (RFC 0171 §B.1).
var errorCodeHTTPStatuses = []int{
	401,
	422,
	422,
	426,
	409,
	400,
	400,
	401,
	403,
	404,
	422,
	401,
	400,
	501,
	400,
	400,
	401,
	403,
	409,
	422,
	422,
	422,
	500,
	403,
	403,
	422,
	403,
	409,
	400,
	409,
	401,
	401,
	500,
	400,
	409,
	410,
	410,
	404,
	401,
	401,
	422,
	422,
	403,
	404,
	400,
	400,
	409,
	400,
	400,
	400,
	409,
	400,
	500,
	400,
	403,
	400,
	400,
	503,
	422,
	400,
	400,
	404,
	400,
	406,
	429,
	422,
	409,
	409,
	404,
	422,
	409,
	403,
	409,
	422,
	503,
	403,
	403,
	422,
	422,
	400,
	401,
	404,
	400,
	400,
	422,
	401,
	400,
	400,
	400,
	409,
	400,
	409,
	403,
	413,
}

// RetriableErrorCodes lists the codes registered retriable: true; retry
// timing lives in Retry-After only (RFC 0171 §B.2).
var RetriableErrorCodes = []string{
	"internal_error",
	"pack_registry_unreachable",
	"rate_limited",
	"residency_unavailable",
	"runner_unavailable",
}

// VendorErrorCodePattern is the grammar of a vendor error code, <org>.<name>,
// without the registry's `(?!openwop\.)` guard (RE2 has no lookahead);
// IsVendorErrorCode applies the reserved-prefix rule.
var VendorErrorCodePattern = regexp.MustCompile(`^[a-z][a-z0-9]*(-[a-z0-9]+)*\.[a-z][a-z0-9_]*$`)

// CapabilityMetadataKeys lists the root metadata keys of the closed v2
// discovery document (capabilities.md §3.1).
var CapabilityMetadataKeys = []string{
	"compliance",
	"configurable",
	"conformance",
	"discovery",
	"engineVersion",
	"eventLogSchemaVersion",
	"extensions",
	"fixtures",
	"implementation",
	"minClientVersion",
	"observability",
	"preferredVersion",
	"protocolVersion",
	"protocolVersions",
	"runtimeCapabilities",
	"testing",
}

// CapabilityFamilyKeys lists the root capability-record keys of the closed
// v2 discovery document (capabilities.md §5–§6).
var CapabilityFamilyKeys = []string{
	"a2a",
	"agentRuntime",
	"agents",
	"aiEnvelope",
	"aiProviders",
	"anonymousActor",
	"artifactTypes",
	"auth",
	"authorization",
	"blobStorage",
	"budget",
	"cache",
	"channelPresence",
	"compensation",
	"connections",
	"content",
	"conversationPrimitive",
	"conversationTurnModelProvenance",
	"credentials",
	"dataResidency",
	"deadLetter",
	"envelopeContracts",
	"envelopeStrictness",
	"envelopes",
	"eventLog",
	"feedback",
	"forms",
	"fs",
	"heartbeat",
	"httpClient",
	"i18n",
	"idempotency",
	"interrupt",
	"kvStorage",
	"limits",
	"mcp",
	"memory",
	"modelCapabilities",
	"multiAgent",
	"multiPartyConversation",
	"nodePackRuntimes",
	"nondeterminismPolicy",
	"nosql",
	"oauth",
	"packs",
	"portability",
	"production",
	"promptLibrary",
	"prompts",
	"providerUsage",
	"purposePropagation",
	"queueBus",
	"replay",
	"sandbox",
	"scheduling",
	"schemaVersions",
	"searchIndex",
	"secrets",
	"selfHostedRunner",
	"sql",
	"subWorkflow",
	"supportedEnvelopes",
	"tableStorage",
	"toolCatalog",
	"toolHooks",
	"triggerBridge",
	"uiPlugins",
	"vectorStore",
	"webhooks",
	"workflowChainPacks",
	"workspace",
}

var errorCodeHTTPStatus = map[string]int{}

var retriableErrorCodeSet = map[string]struct{}{}

var capabilityFamilyKeySet = map[string]struct{}{}

func init() {
	for i, code := range ErrorCodes {
		errorCodeHTTPStatus[code] = errorCodeHTTPStatuses[i]
	}
	for _, code := range RetriableErrorCodes {
		retriableErrorCodeSet[code] = struct{}{}
	}
	for _, key := range CapabilityFamilyKeys {
		capabilityFamilyKeySet[key] = struct{}{}
	}
}

// IsErrorCode reports whether value is a registered protocol error code.
func IsErrorCode(value string) bool {
	_, ok := errorCodeHTTPStatus[value]
	return ok
}

// ErrorCodeHTTPStatus returns the registered HTTP status for a code, or 0
// when the code is not registered.
func ErrorCodeHTTPStatus(code string) int {
	return errorCodeHTTPStatus[code]
}

// IsRetriableErrorCode reports whether value is registered retriable: true.
func IsRetriableErrorCode(value string) bool {
	_, ok := retriableErrorCodeSet[value]
	return ok
}

// IsVendorErrorCode reports whether value is a well-formed vendor code
// (<org>.<name>, openwop. reserved); it does not check org registration.
func IsVendorErrorCode(value string) bool {
	if len(value) >= 8 && value[:8] == "openwop." {
		return false
	}
	return VendorErrorCodePattern.MatchString(value)
}

// IsCapabilityFamilyKey reports whether key is a capability-record key of
// the closed v2 root.
func IsCapabilityFamilyKey(key string) bool {
	_, ok := capabilityFamilyKeySet[key]
	return ok
}
