#!/usr/bin/env node
// generate.mjs — emits src/generated.ts from the vendored v2 registries.
//
// Sources (vendored at CORPUS_TAG by scripts/check-vendored-sync.mjs):
//   spec/v2/errors.json                 → ERROR_CODES / ErrorCode / ERROR_CODE_HTTP_STATUS / RETRIABLE_ERROR_CODES
//   schemas/v2/capabilities.schema.json → CAPABILITY_METADATA_KEYS / CAPABILITY_FAMILY_KEYS
//
// `node scripts/generate.mjs` rewrites src/generated.ts; `--check` exits 1
// when the committed file differs from what the registries produce (the
// sdks:check gate runs it so the union can never drift from the corpus).
//
// Dependency-free (bare `node`).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = join(HERE, '..');
const REPO = join(PKG, '..', '..');
const OUT = join(PKG, 'src', 'generated.ts');

const errors = JSON.parse(readFileSync(join(REPO, 'spec/v2/errors.json'), 'utf8'));
const caps = JSON.parse(readFileSync(join(REPO, 'schemas/v2/capabilities.schema.json'), 'utf8'));

const rows = [...errors.rows].sort((a, b) => a.code.localeCompare(b.code));
const codes = rows.map((r) => r.code);
if (new Set(codes).size !== codes.length) throw new Error('errors.json: duplicate code');
const retriable = rows.filter((r) => r.retriable === true).map((r) => r.code);

// A family is a capability record (RFC 0169 §A): `status` + `witness` are
// required on it. Every other root property is a metadata key (§3.1).
const props = caps.properties ?? {};
const familyKeys = [];
const metadataKeys = [];
for (const [key, schema] of Object.entries(props)) {
  const req = Array.isArray(schema.required) ? schema.required : [];
  (req.includes('status') && req.includes('witness') ? familyKeys : metadataKeys).push(key);
}
familyKeys.sort();
metadataKeys.sort();
if (caps.additionalProperties !== false) throw new Error('capabilities.schema.json: root is not closed');

const list = (items) => items.map((c) => `  '${c}',`).join('\n');

const out = `// GENERATED by scripts/generate.mjs — do not edit.
//
// Sources: spec/v2/errors.json (registry version ${errors.version}, updated ${errors.updated},
// ${codes.length} codes) and schemas/v2/capabilities.schema.json (${familyKeys.length} families,
// ${metadataKeys.length} metadata keys), both vendored at CORPUS_TAG.
// \`npm run generate\` rewrites this file; \`npm run generate:check\` fails on drift.

/** Every registered v2 error code (\`spec/v2/errors.json\`), sorted. */
export const ERROR_CODES = [
${list(codes)}
] as const;

/** A registered protocol error code. A vendor code is \`<org>.<name>\` (see {@link VENDOR_ERROR_CODE_PATTERN}). */
export type ErrorCode = (typeof ERROR_CODES)[number];

/** The registered HTTP status for each code (RFC 0171 §B.1 — a host MUST answer with it). */
export const ERROR_CODE_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
${rows.map((r) => `  '${r.code}': ${r.httpStatus},`).join('\n')}
};

/** The codes registered \`retriable: true\`; retry timing lives in \`Retry-After\` only (RFC 0171 §B.2). */
export const RETRIABLE_ERROR_CODES = [
${list(retriable)}
] as const;

/** Grammar of a vendor error code: \`<org>.<name>\`, \`openwop.\` reserved (\`spec/v2/errors.json\` \`vendorCodePattern\`). */
export const VENDOR_ERROR_CODE_PATTERN = /${errors.vendorCodePattern.replace(/\//g, '\\/')}/;

/** Root metadata keys of the closed v2 discovery document (capabilities.md §3.1). */
export const CAPABILITY_METADATA_KEYS = [
${list(metadataKeys)}
] as const;

/** Root capability-record keys of the closed v2 discovery document (capabilities.md §5–§6). */
export const CAPABILITY_FAMILY_KEYS = [
${list(familyKeys)}
] as const;

export type CapabilityMetadataKey = (typeof CAPABILITY_METADATA_KEYS)[number];
export type CapabilityFamilyKey = (typeof CAPABILITY_FAMILY_KEYS)[number];
`;

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== out) {
    console.error(`  FAIL: ${OUT} is stale — run \`npm run generate\` in sdk/typescript-v2`);
    process.exit(1);
  }
  console.log(`  ok: src/generated.ts matches spec/v2/errors.json (${codes.length} codes) + capabilities.schema.json (${familyKeys.length} families)`);
} else {
  writeFileSync(OUT, out);
  console.log(`wrote ${OUT}: ${codes.length} error codes, ${familyKeys.length} families, ${metadataKeys.length} metadata keys`);
}
