#!/usr/bin/env python3
"""generate.py — emits src/openwop_client/_generated.py from the vendored v2 registries.

Sources (vendored at CORPUS_TAG by scripts/check-vendored-sync.mjs):
    spec/v2/errors.json                 -> ERROR_CODES / ErrorCode / ERROR_CODE_HTTP_STATUS / RETRIABLE_ERROR_CODES
    schemas/v2/capabilities.schema.json -> CAPABILITY_METADATA_KEYS / CAPABILITY_FAMILY_KEYS
    CORPUS_TAG                          -> CORPUS_VERSION (RFC 0219 ``OpenWOP-Client-Version``)

``python3 scripts/generate.py`` rewrites the module; ``--check`` exits 1 when
the committed module differs from what the registries produce (the
sdks:check gate runs it so the code set can never drift from the corpus).

Stdlib only.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PKG = HERE.parent
REPO = PKG.parent.parent
OUT = PKG / "src" / "openwop_client" / "_generated.py"

_CORPUS_TAG = re.compile(
    r"^(?:openwop-conformance/)?v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z.-]+)?$"
)


def corpus_version(tag: str) -> str:
    """RFC 0219: the client names the corpus release it is built against, never
    the package version. ``vX.Y.Z`` / ``openwop-conformance/vX.Y.Z`` / ``X.Y.Z`` ->
    ``X.Y.Z``; a pre-release ``vX.Y.Z-rc.N`` -> ``X.Y`` (the header grammar has no
    pre-release)."""
    m = _CORPUS_TAG.match(tag)
    if not m:
        raise SystemExit(f"CORPUS_TAG: cannot derive a corpus version from {tag!r}")
    return f"{m[1]}.{m[2]}" if m[4] else f"{m[1]}.{m[2]}.{m[3]}"


def main() -> int:
    errors = json.loads((REPO / "spec/v2/errors.json").read_text())
    caps = json.loads((REPO / "schemas/v2/capabilities.schema.json").read_text())
    corpus_tag = (REPO / "CORPUS_TAG").read_text().strip()
    corpus = corpus_version(corpus_tag)

    rows = sorted(errors["rows"], key=lambda r: r["code"])
    codes = [r["code"] for r in rows]
    if len(set(codes)) != len(codes):
        raise SystemExit("errors.json: duplicate code")
    retriable = [r["code"] for r in rows if r.get("retriable") is True]

    # A family is a capability record (RFC 0169 §A): `status` + `witness` are
    # required on it. Every other root property is a metadata key (§3.1).
    family_keys: list[str] = []
    metadata_keys: list[str] = []
    for key, schema in caps.get("properties", {}).items():
        req = schema.get("required") if isinstance(schema, dict) else None
        req = req if isinstance(req, list) else []
        (family_keys if "status" in req and "witness" in req else metadata_keys).append(key)
    family_keys.sort()
    metadata_keys.sort()
    if caps.get("additionalProperties") is not False:
        raise SystemExit("capabilities.schema.json: root is not closed")

    def literal(items: list[str]) -> str:
        return "".join(f'    "{c}",\n' for c in items)

    out = (
        "# GENERATED by scripts/generate.py — do not edit.\n"
        "#\n"
        f"# Sources: spec/v2/errors.json (registry version {errors['version']}, updated "
        f"{errors['updated']}, {len(codes)} codes) and schemas/v2/capabilities.schema.json "
        f"({len(family_keys)} families, {len(metadata_keys)} metadata keys), both vendored at CORPUS_TAG.\n"
        "# `python3 scripts/generate.py` rewrites this file; `--check` fails on drift.\n"
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "import re\n"
        "from typing import Literal\n"
        "\n"
        "ErrorCode = Literal[\n" + literal(codes) + "]\n"
        '"""A registered protocol error code (``spec/v2/errors.json``). A vendor code is\n'
        '``<org>.<name>`` — see :data:`VENDOR_ERROR_CODE_PATTERN`."""\n'
        "\n"
        "ERROR_CODES: frozenset[str] = frozenset(\n    {\n" + literal(codes) + "    }\n)\n"
        '"""Every registered v2 error code."""\n'
        "\n"
        "ERROR_CODE_HTTP_STATUS: dict[str, int] = {\n"
        + "".join(f'    "{r["code"]}": {r["httpStatus"]},\n' for r in rows)
        + "}\n"
        '"""The registered HTTP status for each code (RFC 0171 §B.1)."""\n'
        "\n"
        "RETRIABLE_ERROR_CODES: frozenset[str] = frozenset(\n    {\n" + literal(retriable) + "    }\n)\n"
        '"""The codes registered ``retriable: true``; retry timing lives in ``Retry-After`` only."""\n'
        "\n"
        f'VENDOR_ERROR_CODE_PATTERN = re.compile(r"{errors["vendorCodePattern"]}")\n'
        '"""Grammar of a vendor error code: ``<org>.<name>``, ``openwop.`` reserved."""\n'
        "\n"
        "CAPABILITY_METADATA_KEYS: tuple[str, ...] = (\n" + literal(metadata_keys) + ")\n"
        '"""Root metadata keys of the closed v2 discovery document (capabilities.md §3.1)."""\n'
        "\n"
        "CAPABILITY_FAMILY_KEYS: tuple[str, ...] = (\n" + literal(family_keys) + ")\n"
        '"""Root capability-record keys of the closed v2 discovery document (capabilities.md §5–§6)."""\n'
        "\n"
        f'CORPUS_VERSION = "{corpus}"\n'
        f'"""The corpus release this SDK is built against (``CORPUS_TAG`` {corpus_tag}), sent as\n'
        "``OpenWOP-Client-Version`` on every request (RFC 0219). Not the package version.\"\"\"\n"
    )

    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != out:
            print(f"  FAIL: {OUT} is stale — run `python3 scripts/generate.py` in sdk/python-v2", file=sys.stderr)
            return 1
        print(
            f"  ok: _generated.py matches spec/v2/errors.json ({len(codes)} codes) + "
            f"capabilities.schema.json ({len(family_keys)} families)"
        )
        return 0
    OUT.write_text(out)
    print(f"wrote {OUT}: {len(codes)} error codes, {len(family_keys)} families, {len(metadata_keys)} metadata keys")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
