"""
openwop-client — Python reference SDK for OpenWOP-compliant servers.

Public surface:
    OpenwopClient          — sync HTTP client
    WopError           — typed exception (carries traceparent + traceId)
    RunStatus, StreamMode  — string-typed enums
    All request/response dataclasses

See README.md for usage.
"""

from .client import OpenwopClient
from .errors import WopError
from .events import (
    AgentDecidedPayload,
    AgentHandoffPayload,
    AgentReasonedPayload,
    AgentReasoningDeltaPayload,
    AgentToolCalledPayload,
    AgentToolReturnedPayload,
    MemoryWrittenPayload,
    OutputChunkPayload,
    ReasoningVerbosity,
    agent_decided_payload,
    agent_handoff_payload,
    agent_reasoned_payload,
    agent_reasoning_delta_payload,
    agent_tool_called_payload,
    agent_tool_returned_payload,
    is_agent_decided,
    is_agent_handoff,
    is_agent_reasoned,
    is_agent_reasoning_delta,
    is_agent_tool_called,
    is_agent_tool_returned,
    is_memory_written,
    is_output_chunk,
    memory_written_payload,
    output_chunk_payload,
)
from .sse import stream_events
from .types import (
    AgentDeployment,
    AgentDeploymentTransition,
    AgentInventoryEntry,
    AgentModelClass,
    AgentOrgChart,
    AgentRosterEntry,
    AgentRosterResponse,
    AuditVerifyAnomaly,
    AuditVerifyCheckpoint,
    AuditVerifyResult,
    BulkCancelRunResult,
    BulkCancelRunsRequest,
    BulkCancelRunsResponse,
    Capabilities,
    CapabilitiesA2A,
    CapabilitiesAIProviders,
    CapabilitiesChannelPresence,
    CapabilitiesConversationTurnModelProvenance,
    CapabilitiesGrpc,
    CapabilitiesMultiPartyConversation,
    CapabilitiesRealtimeVoice,
    Annotation,
    CancelRunRequest,
    CancelRunResponse,
    CreateAnnotationRequest,
    CreateRunRequest,
    CreateRunResponse,
    DeploymentState,
    ErrorEnvelope,
    EvalRegression,
    EvalSafetyFinding,
    EvalSummary,
    EvalTaskResult,
    ForkRunRequest,
    ForkRunResponse,
    HTTP_ERROR_CODES,
    InterruptByTokenInspection,
    ListPromptsRequest,
    ListPromptsResponse,
    OrgChartDepartment,
    OrgChartMember,
    OrgChartResponsibilityView,
    PauseRunRequest,
    PauseRunResponse,
    PollEventsResponse,
    PromptKind,
    PromptTemplate,
    PromptVariable,
    RegisterWebhookRequest,
    RegisterWebhookResponse,
    RenderPromptRequest,
    RenderPromptResponse,
    ResolveInterruptRequest,
    ResolveInterruptResponse,
    ResumeRunRequest,
    ResumeRunResponse,
    RunAncestryParent,
    RunAncestryResponse,
    RunConfigurable,
    RunDiffEventDiff,
    RunDiffResponse,
    RunEventDoc,
    RunSnapshot,
    RunStatus,
    StreamMode,
    ToolDescriptor,
    WorkspaceFile,
    PutWorkspaceFileRequest,
    is_http_error_code,
)

__version__ = "1.3.0"

__all__ = [
    "OpenwopClient",
    "WopError",
    "stream_events",
    # Types
    "AuditVerifyAnomaly",
    "AuditVerifyCheckpoint",
    "AuditVerifyResult",
    "BulkCancelRunResult",
    "BulkCancelRunsRequest",
    "BulkCancelRunsResponse",
    "Capabilities",
    "CapabilitiesA2A",
    "CapabilitiesAIProviders",
    "CapabilitiesChannelPresence",
    "CapabilitiesConversationTurnModelProvenance",
    "CapabilitiesGrpc",
    "CapabilitiesMultiPartyConversation",
    "CapabilitiesRealtimeVoice",
    "Annotation",
    "CancelRunRequest",
    "CancelRunResponse",
    "CreateAnnotationRequest",
    "CreateRunRequest",
    "CreateRunResponse",
    "ErrorEnvelope",
    "ForkRunRequest",
    "ForkRunResponse",
    "HTTP_ERROR_CODES",
    "InterruptByTokenInspection",
    "PauseRunRequest",
    "PauseRunResponse",
    "PollEventsResponse",
    "RegisterWebhookRequest",
    "RegisterWebhookResponse",
    "ResolveInterruptRequest",
    "ResolveInterruptResponse",
    "ResumeRunRequest",
    "ResumeRunResponse",
    "RunAncestryParent",
    "RunAncestryResponse",
    "RunConfigurable",
    "RunEventDoc",
    "RunSnapshot",
    "RunStatus",
    "StreamMode",
    "WorkspaceFile",
    "PutWorkspaceFileRequest",
    "is_http_error_code",
    # RFC 0072 / 0081 / 0082 / 0086 / 0087 agent surfaces
    "AgentInventoryEntry",
    "AgentModelClass",
    "AgentDeployment",
    "AgentDeploymentTransition",
    "DeploymentState",
    "AgentRosterEntry",
    "AgentRosterResponse",
    "AgentOrgChart",
    "OrgChartDepartment",
    "OrgChartMember",
    "OrgChartResponsibilityView",
    "EvalSummary",
    "EvalTaskResult",
    "EvalRegression",
    "EvalSafetyFinding",
    # RFC 0078 portable tool catalog
    "ToolDescriptor",
    # RFC 0054 run diff
    "RunDiffResponse",
    "RunDiffEventDiff",
    # RFC 0027 / 0028 prompt library
    "PromptKind",
    "PromptTemplate",
    "PromptVariable",
    "ListPromptsRequest",
    "ListPromptsResponse",
    "RenderPromptRequest",
    "RenderPromptResponse",
    # Typed agent.* event helpers (RFC 0002 + RFC 0024)
    "ReasoningVerbosity",
    "AgentReasonedPayload",
    "AgentReasoningDeltaPayload",
    "AgentToolCalledPayload",
    "AgentToolReturnedPayload",
    "AgentHandoffPayload",
    "AgentDecidedPayload",
    "MemoryWrittenPayload",
    "OutputChunkPayload",
    "is_agent_reasoned",
    "is_agent_reasoning_delta",
    "is_agent_tool_called",
    "is_agent_tool_returned",
    "is_agent_handoff",
    "is_agent_decided",
    "agent_reasoned_payload",
    "agent_reasoning_delta_payload",
    "agent_tool_called_payload",
    "agent_tool_returned_payload",
    "agent_handoff_payload",
    "agent_decided_payload",
    "is_memory_written",
    "memory_written_payload",
    "is_output_chunk",
    "output_chunk_payload",
    # Webhook helpers (SDK-3, 2026-05-15)
    "verify_webhook_signature",
    "sign_webhook_delivery",
    "VerifyValid",
    "VerifyInvalid",
    "DEFAULT_WEBHOOK_FRESHNESS_WINDOW_SECONDS",
    # Registry-read helpers (SDK-5, 2026-05-15)
    "RegistryClient",
    "RegistryDiscovery",
    "RegistryIndex",
    "RegistryIndexEntry",
    "RegistryPackMetadata",
    "RegistryVersionManifest",
    "__version__",
]

from .webhook_helpers import (
    DEFAULT_WEBHOOK_FRESHNESS_WINDOW_SECONDS,
    VerifyInvalid,
    VerifyValid,
    sign_webhook_delivery,
    verify_webhook_signature,
)

from .registry_helpers import (
    RegistryClient,
    RegistryDiscovery,
    RegistryIndex,
    RegistryIndexEntry,
    RegistryPackMetadata,
    RegistryVersionManifest,
)
